### PR TITLE
Some new paint

### PR DESCRIPTION
**Pull request by TheJaredWilcurt**
Look through the comments for each commit for specific details.

or...

**TLDR:**
- Updated Package.json
- Cleaned up files
- Added more Sass files and set up a common project structure
- Added detailed instructions in the README and changed all gulp commands to npm ones so you don't need gulp globally installed to run them.

### CODE REVIEW

**Comment by lwakefield** [comment]
Hi Jared,

I appreciate your contributions!
Minifying and prettifying the screenshot was something I should have done given more time!
Thanks for making the `readme.md` and `package.json` more complete and correct as well as working on compatibility.

I feel like a lot of your contributions, although technically correct, add un-necessary complexity to something I intended as a very simple demo.

Let me expand on that further.
- Pulling in more .sass files seems un-necessary (from 36->275 lines of css, ~650% increase in size).
- Adding npm bindings for a project which is meant to primarily about gulp seems un-necessary.
- I prefer not to use @import as it [causes assets to load sequentially, blocking concurrent loading](https://varvy.com/pagespeed/avoid-css-import.html). Though I agree that it feels better than adding it to html.
- `<html>` tags are implied when using HTML (more specifically, not XHTML). [see here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html)

Please let me know what you think about those comments!

**Comment by TheJaredWilcurt** [comment]
In Sass, `@import` is a positive thing. There is no blocking.

It pulls in all the files into one file (concatenation), then applies your settings for minification. An `@import` of a Sass file will be converted to concatenation.

The only item that remains being imported is the font, and you very much want that to occur. For example, if you have a `background-image` applied to something in your CSS, the browser will not download that image unless the element it is applied to is in use on the page. The moment that item appears on the page, it will apply the CSS for it, see that the image hasn't been downloaded and _then_ make a network request for it. The same is true for fonts. I could `@import` 10,000 fonts at the top of my CSS document, but until an element on the page actually uses one of them, it doesn't get downloaded. This is especially true with Google web fonts, which allow you to specify multiple weights in a single import (such as 300,400,500). Only the weights in use on the current page will be downloaded.

If you compare that to the HTML linking of web fonts and embedding of images (`<link>` ``), _these_ are in fact blocking, and will require the browser to make a network request the moment that line in the HTML is hit, whether or not that font is used, or that image is visible.

So, in Sass, `@import` of other CSS is your friend. In HTML and CSS, linking to webfonts is a far better experience when done with CSS.

---

I do agree though that there are a lot of Sass files. I only added them in to pad out the structure of the main Sass file, to show how to organize your CSS.

---

The node scripts are a convenience. They have the benefit of running the project's version of Gulp, rather than the global version which may not match or be compatible in the future (or even in the present, if someone is intentionally using an older version). It adds stability to the project. I'm not against mentioning both in the README though:

> Run either one of these commands to build the minified version, `npm run prod` or `gulp --production`.

I'm not sure if that clarifies what's happening to people more, or makes it more confusing (why would you list two different ways to do the same thing).

---

[I know that `<html>` tags are implied, but so is `<head>` and `<body>`](https://www.youtube.com/watch?v=WjP7TEKB7Uo&t=4m40s). Just because the browser goes out of it's way to make a page work if it isn't written properly, doesn't mean you should take that as a license to write less readable code.

> "Premature optimization is the root of all evil." - [Standford Algorithms Expert, Donald Knuth](https://xkcd.com/163/)

---

I'll go through and make modifications based on your feedback and send back the compromise for you to look over.

**Comment by TheJaredWilcurt** [comment]
@lwakefield Updated

**Comment by lwakefield** [comment]
Hi Jared,

Thanks for your work and sorry for the slow response!

As far as I know, @import will pull in local files, but if the @import points toward a url, it will not pull these files into the compiled .css

Cheers,
Lawrence

**Comment by TheJaredWilcurt** [comment]
Awesome! :grinning:

**Pull request merged**
